### ISSUE TITLE
Redactar README explicativo

### ISSUE THREAD

**Issue by abenassi** [lchittaro-old/preciosconstantes#2]
Un _README.md_ debería explicar brevemente lo que contiene el repo, dar algo de contexto para que el usuario empiece a entender qué tiene acá y linkear a los recursos relevantes (que en este caso pueden ser (1) el/los link/s de la/s visualizaciones, (2) el link a la documentación metodológica y (3) el link a los datos crudos.

**Comment by lautarochittaro** [comment]
listo. Los link faltan porque hay que primero subirlo a la página
